version: '3'

networks:
  v3-net:
    name: v3-net
    external: true

services:
  node-app:
    image: node-app:0.1.0
    container_name: node_app
    ports:
      - "8000:8000"
    networks:
      - v3-net
    restart: always
    environment:
      - TZ=UTC