apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemo
  labels:
    app: mydemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydemo
  template:
    metadata:
      labels:
        app: mydemo
    spec:
      containers:
        - name: mydemo
          image: anhit98/mydemo:v0.1.0
          ports:
            - containerPort: 8080